/**
 * WhatsApp delivery service.
 * 
 * Status: WhatsApp messages are generated by AI and stored in automation_log
 * with status "queued". When Meta WhatsApp Business API verification is complete,
 * swap the `deliverWhatsApp` function body to call the Meta API.
 * 
 * Nothing changes in the callers — just update this file.
 */

export interface WhatsAppMessage {
  to: string;
  body: string;
}

export async function deliverWhatsApp(msg: WhatsAppMessage): Promise<void> {
  // TODO: Replace with Meta WhatsApp Business API call once credentials are ready.
  // Example:
  // await fetch(`https://graph.facebook.com/v18.0/${PHONE_NUMBER_ID}/messages`, {
  //   method: "POST",
  //   headers: { Authorization: `Bearer ${WHATSAPP_TOKEN}`, "Content-Type": "application/json" },
  //   body: JSON.stringify({ messaging_product: "whatsapp", to: msg.to, type: "text", text: { body: msg.body } }),
  // });
  
  // For now: no-op. Message is already logged in automation_log.
  void msg;
}
